### ISSUE TITLE
Sidebar replacement

### ISSUE THREAD

**Issue by phoet** [typus/typus#430]
I was using the old sidebar functionality described here: http://docs.typuscmf.com/customization/user-interface.html#dashboard

It looks like this is gone, but i did not find a reference in the changelog. Is there currently some similar functionality to add custom actions to the dashboard?

**Comment by phillipoertel** [comment]
Hi Peter, I'm not sure what your ping us about...
In any case, unfortunately I can't help you at the moment sinxe I'm off for a few months, I don't even have access to a dev machine right now. If you need something from torial, best to contact them directly. Or maybe Francesc can help. 
cheers, phillip

**Comment by phoet** [comment]
Wrong Browser tab, sorry!

Phillip Oertel <notifications@github.com> schrieb am Di., 23. Juni 2015
02:38:
