### ISSUE TITLE
editor is redirected to not_allowed after updating their profile

### ISSUE THREAD

**Issue by meleyal** [typus/typus#480]
Currently if an admin user updates their profile they are redirected to `admin_users/index`.

But if they don't have read access to `AdminUser` (e.g. editor role) they are not allowed to see this action, so they get redirected to the `not_allowed` action.

**Comment by fesplugas** [comment]
https://github.com/typus/typus/commit/b869b54551331f4b79dc6d05895fcadc6bd83bd1

**Comment by fesplugas** [comment]
cherry picked your commit https://github.com/typus/typus/commit/76e30c3900e5a8338e2aaa7b2d76aae0ed77e19f
