### ISSUE TITLE
Look for new mantainers

### ISSUE THREAD

**Issue by fesplugas** [typus/typus#488]

**Comment by takashi** [comment]
@fesplugas this project will not be maintained until new maintainer is found?

**Comment by fesplugas** [comment]
It will be mantained when I have time to mantain it. Like today ...

**Comment by fesplugas** [comment]
For the moment, I'll be accepting new code and PR.

**Comment by takashi** [comment]
@fesplugas I see, thank you for maintaining this awesome project :)
