### ISSUE TITLE
Typus don't have "rails generate typus:model" command?

### ISSUE THREAD

**Issue by baban** [typus/typus#494]
Duaring developping, blueprint is changed, and I create new model,
Typus need to input command like a below for create new YAML and controller.

```
rails generate typus
git add config/typus/newmodel.yml app/controller/admin/newmodel_controller.rb
git clean -dfx
```

It is so irritated. I want to input like below.

```
rails generate typus:model newmodel
```

I guess it is very useful!!

**Comment by fesplugas** [comment]
Pull requests are accepted.

**Comment by baban** [comment]
Okay!
I'll try it now!!

https://github.com/baban/typus/tree/model_generator
