### ISSUE TITLE
Make tests pass in "mantained" branches

### ISSUE THREAD

**Issue by fesplugas** [typus/typus#495]
- [x] master
- [ ] 4-0-stable
- [ ] 4-2-stable

**Comment by tkoenig** [comment]
Just want to remind you that there is still one invalid test in master, see wollzelle/typus@2f8a457bff3251be6b77277b12d97f58207306f3

**Comment by fesplugas** [comment]
@tkoenig I'm organizing things to be able to start working on some of the current issues.

**Comment by tkoenig** [comment]
:+1:

**Comment by fesplugas** [comment]
![image](https://cloud.githubusercontent.com/assets/2720/7296076/b7af9008-e9bc-11e4-8045-9f27f1ad83ed.png)
